addons:
sonarcloud:
organization:"bet"
token:"6a1dad303313158bfc1590911feb12a948c8e909"	
script:
		#	the	following	command	line	builds	the	project,	runs	the	tests	with	coverage
		# and	then	execute	the	SonarCloud	analysis
		-mvn clean	org.jacoco:jacoco-maven-plugin:prepare-agent org.jacoco:jacocomaven-plugin:report	 install	sonar:sonar